export const en = {
  proctree: {
    loading: "Loading process tree...",
  },
  vmexplorer: {
    backToProctree: "Process Tree",
    title: "Virtual Memory Explorer",
    pidBadge: "pid:",
    startTimeBadge: "start_time:",
    commBadge: "comm:",
    noEntries: "No entries",
    entries: "entries",
    lvlRoot: "PGD ROOT",
    lvl4: "PGD",
    lvl3: "PUD",
    lvl2: "PMD",
    lvl1: "PTE",
    pageUpper: "PAGE",
    pageTableUpper: "PGTBL",
    entryRaw: "Raw(HEX)",
    entryPA: "PA",
    entryKernelVA: "KERNEL VA",
    entryUserVA: "USER VA",
  },
};
